/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlgemeneVoorwaardenRouteImport } from './routes/algemene-voorwaarden'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as PrivacyverklaringRouteImport } from './routes/privacyverklaring'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgemeneVoorwaardenRoute = AlgemeneVoorwaardenRouteImport.update({
  id: '/algemene-voorwaarden',
  path: '/algemene-voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyverklaringRoute = PrivacyverklaringRouteImport.update({
  id: '/privacyverklaring',
  path: '/privacyverklaring',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/intake': typeof IntakeRoute
  '/privacyverklaring': typeof PrivacyverklaringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/intake': typeof IntakeRoute
  '/privacyverklaring': typeof PrivacyverklaringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/intake': typeof IntakeRoute
  '/privacyverklaring': typeof PrivacyverklaringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/algemene-voorwaarden' | '/intake' | '/privacyverklaring'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/algemene-voorwaarden' | '/intake' | '/privacyverklaring'
  id:
    | '__root__'
    | '/'
    | '/algemene-voorwaarden'
    | '/intake'
    | '/privacyverklaring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlgemeneVoorwaardenRoute: typeof AlgemeneVoorwaardenRoute
  IntakeRoute: typeof IntakeRoute
  PrivacyverklaringRoute: typeof PrivacyverklaringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algemene-voorwaarden': {
      id: '/algemene-voorwaarden'
      path: '/algemene-voorwaarden'
      fullPath: '/algemene-voorwaarden'
      preLoaderRoute: typeof AlgemeneVoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacyverklaring': {
      id: '/privacyverklaring'
      path: '/privacyverklaring'
      fullPath: '/privacyverklaring'
      preLoaderRoute: typeof PrivacyverklaringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlgemeneVoorwaardenRoute: AlgemeneVoorwaardenRoute,
  IntakeRoute: IntakeRoute,
  PrivacyverklaringRoute: PrivacyverklaringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
